messages:
    prefix: 'PREFIX ->'
    teleported: 'Telportiere...'
    expired: 'Die Anfrage ist abgelaufen.'
    tpa: 'Du hast eine TPA von %player% erhalten.'
    tpahere: 'Du hast eine TPAHere von %player% erhalten.'
    accepttpa: '[Akzeptieren]'
    denytpa: '[Ablehnen]'
    sent: 'Die Anfrage wurde gesendet.'
    target_offline: 'Der angegebene Spieler ist offline.'
    unknown_target: 'Dieser Spieler ist unbekannt.'
    usage_tpa: 'Bitte benutze: /tpa <Spieler>'
    usage_tpahere: 'Bitte benutze: /tpahere <Spieler>'
    usage_tp: 'Bitte benutze: /tp <Spieler>'
    usage_tphere: 'Bitte benutze: /tphere <Spieler>'
    usage_tpohere: 'Bitte benutze: /tpohere <Spieler>'
    usage_tpdeny: 'Bitte benutze: /tpdeny <Spieler>'
    usage_tpaccept: 'Bitte benutze: /tpaccept <Spieler>'
    usage_tpacancel: 'Bitte benutze: /tpacancel <Spieler>'
    usage_tpoffline: 'Bitte benutze: /tpoffline <Spieler>'
    no_perm: 'Du hast keine Berechtigung diesen Befehl zu nutzen.'
    tp_blocked: 'Dieser Spieler nimmt keine Teleportationanfragen an.'
    tp_not_expired: 'Du hast noch eine ausgehende TP Anfrage. Benutze /tpcancel um weitere Anfragen senden zu können.'
    can_not_safetp: 'Es konnte keine sichere Position gefunden werden.'
    tpdenied: 'Deine Telportationsanfrage wurde abgelehnt.'
    tpdeny: 'Du hast diese Anfrage abgelehnt.'
    tptoggled_on: 'Du nimmst nun Teleportanfragen an.'
    tptoggled_off: 'Du nimmst nun keine Teleportanfragen mehr an.'
    no_tpreq: 'Du hast keine ausstehende Anfrage von diesem Spieler.'
    tpa_aborted: 'Die Teleportationsanfrage wurde zurückgezogen.'
    tpa_canceled: '%player% hat die Teleportationsanfrage zurückgezogen.'
    tpa_all_players: 'Du hast allen Spielern eine Teleportationsanfrage gesendet.'
    tp_all_players: 'Du hast alle Spieler zu dir teleportiert.'
    tp_all_player_ext: '(Spieler: %player%)'
    tpa_accepted: '%player% hat deine TPA akzeptiert.'
    tpahere_accepted: '%player% hat deine TPAHere akzeptiert.'
    tp_not_allowed: 'Dieser Vorgang ist nicht erlaubt.'
    tp_not_allowed_nether: 'Du darfst dich nicht in den Nether teleportieren.'
    tp_not_allowed_end: 'Du darfst dich nicht in das End teleportieren.'
    LACK_GESOFFEN: 'HAST DU EIN MAßBAND GEFUTTERT?!'
    no_outgoing_tpa: 'Du hast keine ausstehende Anfrage.'
    on_cooldown: 'Du darfst noch keine neue Anfrage stellen.'
options:
    tpa_expire: 300
    tpa_cooldown: 300
    tpa_sent_cooldown: 10