name: TP
version: 1.10.2
api-version: 1.17
depend:
    - NBTAPI
author: Neo8
main: de.neo.prodtp.ProdTPMain
commands:
    prodtpver:
    tpaall:
    tpacancel:
    tpaccept:
    tpa:
    tpahere:
    tpall:
    tp:
    tpdeny:
    tphere:
    tpo:
    tpohere:
    tptoggle:
    tpoffline: